"""First migration

Revision ID: c4b7194dcdbe
Revises: 1
Create Date: 2023-05-30 12:27:26.668110

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4b7194dcdbe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mp3",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mp3", sa.LargeBinary(), nullable=True),
        sa.Column("file_name", sa.String(length=150), nullable=True),
        sa.Column("create_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="wav_to_mp3",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=False
        ),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("token", sa.UUID(), nullable=False),
        sa.Column("create_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("modified_date", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id", "token"),
        sa.UniqueConstraint("email"),
        schema="wav_to_mp3",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users", schema="wav_to_mp3")
    op.drop_table("mp3", schema="wav_to_mp3")
    # ### end Alembic commands ###
