version: "3.9"

services:
  wav_to_mp3_api:
    environment:
      - COMPOSE_PROJECT_NAME
    container_name: wav_to_mp3_api
    build:
      context: .
      dockerfile: dockerfile_wav_to_mp3
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    command: bash -c "
      alembic upgrade head
      && uvicorn main:app --host ${HOST} --port ${PORT} --workers ${UVICORN_WORKERS}
      "
    depends_on:
      - postgres

  postgres:
    container_name: postgres_wav_to_mp3
    image: postgres:13-alpine3.15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_volume:

